FROM node:22-alpine
WORKDIR /app

# Point to the sub-directory where the files actually live
COPY frontend/package*.json ./
RUN npm install --legacy-peer-deps

COPY frontend/ . 

EXPOSE 3000
ENV NODE_ENV=development
ENV WATCHPACK_POLLING=true
CMD ["npm", "run", "dev"]