services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    env_file:
      - .env

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: python -m alembic upgrade head
    restart: "no"
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    volumes:
      - .:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - INTERNAL_API_URL=http://api:8000
    depends_on:
      - api
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/frontend/.next

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    user: root
    environment:
      # - DOCKER_HOST=tcp://host.docker.internal:2375
      - HOST_PROJECT_ROOT=${HOST_PROJECT_ROOT}
      - HOST_SANDBOX_ROOT=${HOST_SANDBOX_ROOT}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/sandbox:/sandbox/jobs
      - ./infra/seccomp.json:/etc/rce/seccomp.json:ro
      - .:/app
    command: celery -A worker.app worker --loglevel=info --concurrency=2
    env_file:
      - .env

  beat:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    command: celery -A worker.app beat --loglevel=info --schedule=/tmp/celerybeat-schedule
    env_file:
      - .env

volumes:
  postgres_data:
  sandbox_data:
