"""Add ProblemLanguageConfig

Revision ID: 078d58f2536c
Revises: d027e0854985
Create Date: 2026-05-06 08:50:49.731205
"""

from alembic import op
import sqlalchemy as sa


revision = "078d58f2536c"
down_revision = "d027e0854985"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "problem_language_configs",
        sa.Column("problem_id", sa.UUID(), nullable=False),
        sa.Column(
            "language",
            sa.Enum("python", "cpp", "java", "nodejs", name="supported_language_enum"),
            nullable=False,
        ),
        sa.Column("boilerplate", sa.Text(), nullable=False),
        sa.Column("driver_code", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("problem_id", "language"),
    )
    op.drop_index(
        op.f("idx_submissions_status"),
        table_name="submissions",
        postgresql_where="(status <> 'completed'::submission_status)",
    )
    op.drop_index(op.f("idx_submissions_problem"), table_name="submissions")
    op.create_index(
        "idx_submissions_problem", "submissions", ["problem_id", "created_at"], unique=False
    )
    op.drop_index(op.f("idx_submissions_user"), table_name="submissions")
    op.create_index("idx_submissions_user", "submissions", ["user_id", "created_at"], unique=False)
    op.drop_index(op.f("idx_users_email"), table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.drop_index("idx_submissions_user", table_name="submissions")
    op.create_index(
        op.f("idx_submissions_user"),
        "submissions",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index("idx_submissions_problem", table_name="submissions")
    op.create_index(
        op.f("idx_submissions_problem"),
        "submissions",
        ["problem_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_submissions_status"),
        "submissions",
        ["status"],
        unique=False,
        postgresql_where="(status <> 'completed'::submission_status)",
    )
    op.drop_table("problem_language_configs")
    # ### end Alembic commands ###
