"""Add difficulty to problems

Revision ID: 7b94b80a08cb
Revises: 0002
Create Date: 2026-05-05 06:21:01.190638
"""

from alembic import op
import sqlalchemy as sa


revision = "7b94b80a08cb"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE difficulty_enum AS ENUM ('easy', 'medium', 'hard')")
    op.add_column(
        "problems",
        sa.Column(
            "difficulty",
            sa.Enum("easy", "medium", "hard", name="difficulty_enum"),
            server_default=sa.text("'medium'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("problems", "difficulty")
    op.execute("DROP TYPE difficulty_enum")
    # ### end Alembic commands ###
