"""add_submission_batch_state

Revision ID: 8daa7f2d498a
Revises: fe92cb2cbc88
Create Date: 2026-05-06 10:11:01.993909
"""
from alembic import op
import sqlalchemy as sa


revision = '8daa7f2d498a'
down_revision = 'fe92cb2cbc88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('is_submit', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False))
    op.add_column('submissions', sa.Column('passed_test_cases', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('submissions', sa.Column('total_test_cases', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('submissions', sa.Column('failed_test_case_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'submissions', 'test_cases', ['failed_test_case_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'failed_test_case_id')
    op.drop_column('submissions', 'total_test_cases')
    op.drop_column('submissions', 'passed_test_cases')
    op.drop_column('submissions', 'is_submit')
    # ### end Alembic commands ###
