"""Add topics and hints

Revision ID: d027e0854985
Revises: 7b94b80a08cb
Create Date: 2026-05-05 06:38:31.251491
"""

from alembic import op
import sqlalchemy as sa


revision = "d027e0854985"
down_revision = "7b94b80a08cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "problem_topics",
        sa.Column("problem_id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("problem_id", "topic_id"),
    )
    op.add_column(
        "problems", sa.Column("hints", sa.ARRAY(sa.String()), server_default="{}", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("problems", "hints")
    op.drop_table("problem_topics")
    op.drop_table("topics")
    # ### end Alembic commands ###
