"""add_actual_and_expected_output_to_submissions

Revision ID: fe92cb2cbc88
Revises: 078d58f2536c
Create Date: 2026-05-06 09:57:01.252749
"""
from alembic import op
import sqlalchemy as sa


revision = 'fe92cb2cbc88'
down_revision = '078d58f2536c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('actual_output', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('expected_output', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'expected_output')
    op.drop_column('submissions', 'actual_output')
    # ### end Alembic commands ###
