"""Celery tasks: evaluate_submission, sweep_zombies, sweep_sandbox_dirs."""

from __future__ import annotations

import os
import json
import shutil
import time
from collections.abc import Callable
from pathlib import Path
from typing import Any, TypeVar, cast

import redis as _redis_sync
from celery import Task
from sqlalchemy import text
from sqlalchemy.engine import CursorResult

from config.settings import settings
from db.sync_session import get_sync_db
from shared.enums import Verdict
from worker.app import app
from worker.compile import run_compile_container
from worker.execute import execute_driver_code
from worker.fairness import compute_fair_limits
from worker.runners import LANGUAGE_CONFIG
from worker.sandbox import cleanup_sandbox, prepare_sandbox

_redis = _redis_sync.from_url(settings.REDIS_URL, decode_responses=True)

F = TypeVar("F", bound=Callable[..., object])


def _typed_task(*args: Any, **kwargs: Any) -> Callable[[F], F]:
    return cast(Callable[[F], F], app.task(*args, **kwargs))


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _check_verdict(actual_str: str | None, expected_str: str | None) -> Verdict:
    """Safely compare the JSON output generated by the driver with the expected output."""
    if not actual_str:
        return Verdict.WA
        
    if actual_str.startswith("Runtime Error"):
        return Verdict.RE
        
    try:
        # Compare as parsed JSON objects to ignore formatting/spacing differences
        return Verdict.ACC if json.loads(actual_str) == json.loads(expected_str) else Verdict.WA
    except (json.JSONDecodeError, TypeError):
        # Fallback to strict string matching if parsing fails
        return Verdict.ACC if str(actual_str).strip() == str(expected_str).strip() else Verdict.WA


def _finalise(
    job_id: str,
    verdict: Verdict,
    exec_time_ms: int,
    memory_mb: int,
    stdout_snippet: str,
    stderr_snippet: str,
    passed_cases: int = 0,
    total_cases: int = 0,
    failed_tc_id: Any | None = None,
    actual: str | None = None,
    expected: str | None = None,
) -> None:
    """Write final result to PostgreSQL and publish to Redis Pub/Sub."""
    clean_stdout = stdout_snippet.strip()[:1000] if stdout_snippet else None
    clean_stderr = stderr_snippet.strip()[:512] if stderr_snippet else None

    with get_sync_db() as db:
        db.execute(
            text("""
                UPDATE submissions
                SET status = 'completed',
                    verdict = :verdict,
                    execution_time_ms = :exec_time_ms,
                    memory_used_mb = :memory_mb,
                    stdout_snippet = :stdout_snippet,
                    stderr_snippet = :stderr_snippet,
                    passed_test_cases = :passed,
                    total_test_cases = :total,
                    failed_test_case_id = :failed_id,
                    actual_output = :actual,
                    expected_output = :expected
                WHERE id = :job_id
            """),
            {
                "verdict": verdict.value,
                "exec_time_ms": exec_time_ms,
                "memory_mb": memory_mb,
                "stdout_snippet": clean_stdout,
                "stderr_snippet": clean_stderr,
                "passed": passed_cases,
                "total": total_cases,
                "failed_id": failed_tc_id,
                "actual": actual,
                "expected": expected,
                "job_id": job_id,
            },
        )

    payload = {
        "job_id": job_id,
        "status": "completed",
        "verdict": verdict.value,
        "execution_time_ms": exec_time_ms,
        "memory_used_mb": memory_mb,
        "stdout_snippet": clean_stdout,
        "stderr_snippet": clean_stderr,
        "passed_test_cases": passed_cases,
        "total_test_cases": total_cases,
        "failed_test_case_id": str(failed_tc_id) if failed_tc_id else None,
        "actual_output": actual,
        "expected_output": expected,
    }
    _redis.publish(f"job_updates:{job_id}", json.dumps(payload))


def _finalise_run(
    job_id: str,
    verdict: Verdict,
    exec_time_ms: int,
    memory_mb: int,
    stdout_snippet: str,
    stderr_snippet: str,
    passed_cases: int,
    total_cases: int,
    details: list[dict],
) -> None:
    """Finalise a Run Code execution."""
    clean_stdout = stdout_snippet.strip()[:1000] if stdout_snippet else None
    clean_stderr = stderr_snippet.strip()[:512] if stderr_snippet else None

    with get_sync_db() as db:
        db.execute(
            text("""
                UPDATE submissions
                SET status = 'completed',
                    verdict = :verdict,
                    execution_time_ms = :exec_time_ms,
                    memory_used_mb = :memory_mb,
                    stdout_snippet = :stdout_snippet,
                    stderr_snippet = :stderr_snippet,
                    passed_test_cases = :passed,
                    total_test_cases = :total
                WHERE id = :job_id
            """),
            {
                "verdict": verdict.value,
                "exec_time_ms": exec_time_ms,
                "memory_mb": memory_mb,
                "stdout_snippet": clean_stdout,
                "stderr_snippet": clean_stderr,
                "passed": passed_cases,
                "total": total_cases,
                "job_id": job_id,
            },
        )

    payload = {
        "job_id": job_id,
        "status": "completed",
        "verdict": verdict.value,
        "execution_time_ms": exec_time_ms,
        "memory_used_mb": memory_mb,
        "stdout_snippet": clean_stdout,
        "stderr_snippet": clean_stderr,
        "passed_test_cases": passed_cases,
        "total_test_cases": total_cases,
        "details": details,
    }
    _redis.publish(f"job_updates:{job_id}", json.dumps(payload))
    _redis.setex(f"run_details:{job_id}", 3600, json.dumps(details))


# ---------------------------------------------------------------------------
# Main task
# ---------------------------------------------------------------------------

@_typed_task(bind=True, max_retries=0, name="worker.tasks.evaluate_submission")
def evaluate_submission(self: Task, job_id: str) -> None:
    """Evaluate test cases for a submission using Isolated Execution."""
    job_dir: Path | None = None

    try:
        # --- 1. Atomic pending → running ---
        with get_sync_db() as db:
            transition_result = cast(
                CursorResult[Any],
                db.execute(
                    text(
                        "UPDATE submissions SET status='running' "
                        "WHERE id=:id AND status='pending' RETURNING id"
                    ),
                    {"id": job_id},
                ),
            )

            if transition_result.rowcount == 0:
                print(f"Submission {job_id} already running or completed — dropping task")
                return
            db.commit()

            submission_row = db.execute(
                text("SELECT language, code, problem_id, is_submit FROM submissions WHERE id=:id"),
                {"id": job_id},
            ).fetchone()
            if submission_row is None:
                _finalise(job_id, Verdict.IE, 0, 0, "", "Submission not found")
                return

            language = submission_row.language
            code = submission_row.code
            problem_id = submission_row.problem_id
            is_submit: bool = submission_row.is_submit

            problem_row = db.execute(
                text("SELECT base_time_limit_ms, base_memory_limit_mb FROM problems WHERE id=:id"),
                {"id": problem_id},
            ).fetchone()
            if problem_row is None:
                _finalise(job_id, Verdict.IE, 0, 0, "", "Problem not found")
                return

            tc_query = "SELECT id, input_data, expected_output FROM test_cases WHERE problem_id=:pid"
            if not is_submit:
                tc_query += " AND is_sample=TRUE"
            tc_query += " ORDER BY ordering ASC"

            test_cases = db.execute(text(tc_query), {"pid": problem_id}).fetchall()
            if not test_cases:
                _finalise(job_id, Verdict.IE, 0, 0, "", "No test cases found for problem")
                return

            config_row = db.execute(
                text(
                    "SELECT driver_code FROM problem_language_configs "
                    "WHERE problem_id=:pid AND language=:lang"
                ),
                {"pid": problem_id, "lang": getattr(language, "value", language)},
            ).fetchone()
            if config_row is None:
                _finalise(job_id, Verdict.IE, 0, 0, "", "No language config for problem")
                return

        # --- 2. Compute fair limits ---
        limits = compute_fair_limits(
            language, problem_row.base_time_limit_ms, problem_row.base_memory_limit_mb
        )

        # --- 3. Prepare sandbox & Code ---
        runner = LANGUAGE_CONFIG[language]
        print(f"Evaluating {job_id} (is_submit={is_submit}, lang={language})")

        secure_driver = config_row.driver_code.replace("{job_id}", str(job_id))
        if "{user_code}" in secure_driver:
            final_code = secure_driver.replace("{user_code}", code)
        else:
            final_code = f"{code}\n\n{secure_driver}"

        # Standard preparation (writes the code file)
        job_dir = prepare_sandbox(
            job_id=job_id,
            source_code=final_code,
            source_filename=runner.source_file,
            test_inputs=[], # We leave this empty because we handle inputs via JSON now
        )

        # --- 4. Write testcases.json ---
        formatted_tc = []
        for tc in test_cases:
            formatted_tc.append({
                "input": json.loads(tc.input_data),
                "expected_output": tc.expected_output
            })
            
        with open(job_dir / "testcases.json", "w", encoding="utf-8") as f:
            json.dump(formatted_tc, f)

        os.chmod(job_dir, 0o777)
        
        image = f"rce-{language}:latest"

        # --- 5. Compile (if needed) ---
        if runner.compile_cmd:
            success = run_compile_container(
                job_dir=job_dir,
                image=image,
                compile_cmd=runner.compile_cmd,
                compile_artifact=runner.compile_artifact,
            )
            if not success:
                ce_file = job_dir / "compile_err.txt"
                ce_err = ce_file.read_text(encoding="utf-8", errors="replace")[:1024] if ce_file.exists() else ""
                _finalise(job_id, Verdict.CE, 0, limits.memory_mb, "", ce_err)
                return

        # --- 6. Execute Container ONCE ---
        # Global timeout: allow enough time to run all test cases plus a buffer
        global_timeout = (limits.time_sec * len(test_cases)) + 5
        
        success, fatal_error = execute_driver_code(
            job_dir=job_dir,
            image=image,
            run_cmd=runner.run_cmd.split(),
            memory_mb=limits.memory_mb,
            timeout_sec=global_timeout
        )

        # --- 7. Evaluate structured JSON Output ---
        results_file = job_dir / "run_results.json"
        if not results_file.exists():
            # If the driver crashed before writing the file (e.g. infinite loop killed by Python, or Syntax Error)
            verdict = Verdict.TLE if "Time Limit" in fatal_error else Verdict.RE
            _finalise(job_id, verdict, 0, limits.memory_mb, "", fatal_error)
            return

        with open(results_file, "r") as f:
            run_data = json.load(f)

        exec_time_ms = run_data.get("execution_time_ms", 0)
        tc_results = run_data.get("test_case_results", [])
        
        total_cases = len(test_cases)
        passed_cases = 0
        user_logs_parts: list[str] = []
        
        if is_submit:
            # PATH B: Fail-Fast evaluation for Submit
            verdict = Verdict.ACC
            failed_tc_id = None
            actual_for_db = None
            expected_for_db = None

            for res in tc_results:
                idx = res["test_case_index"]
                tc = test_cases[idx]
                actual = res["actual_output"]
                expected = res["expected_output"]
                
                if res["stdout"]:
                    user_logs_parts.append(res["stdout"])

                tc_verdict = _check_verdict(actual, expected)

                if tc_verdict == Verdict.ACC:
                    passed_cases += 1
                else:
                    # FAIL FAST
                    verdict = tc_verdict
                    failed_tc_id = tc.id
                    actual_for_db = actual
                    expected_for_db = expected
                    break

            combined_logs = "\n\n".join(user_logs_parts)
            _finalise(
                job_id=job_id,
                verdict=verdict,
                exec_time_ms=exec_time_ms,
                memory_mb=limits.memory_mb,
                stdout_snippet=combined_logs,
                stderr_snippet=fatal_error,
                passed_cases=passed_cases,
                total_cases=total_cases,
                failed_tc_id=failed_tc_id,
                actual=actual_for_db,
                expected=expected_for_db,
            )
            
        else:
            # PATH A: Full evaluation for Run Code
            details: list[dict] = []
            verdict = Verdict.ACC

            for res in tc_results:
                idx = res["test_case_index"]
                tc = test_cases[idx]
                actual = res["actual_output"]
                expected = res["expected_output"]
                stdout = res["stdout"]
                
                if stdout:
                    user_logs_parts.append(stdout)

                tc_verdict = _check_verdict(actual, expected)
                if tc_verdict == Verdict.ACC:
                    passed_cases += 1
                else:
                    verdict = Verdict.WA

                details.append({
                    "test_case_id": str(tc.id),
                    "input": tc.input_data,
                    "expected": expected,
                    "actual": actual,
                    "verdict": tc_verdict.value,
                    "stdout": stdout,
                })

            combined_logs = "\n\n".join(user_logs_parts)
            _finalise_run(
                job_id=job_id,
                verdict=verdict,
                exec_time_ms=exec_time_ms,
                memory_mb=limits.memory_mb,
                stdout_snippet=combined_logs,
                stderr_snippet=fatal_error,
                passed_cases=passed_cases,
                total_cases=total_cases,
                details=details,
            )

        print(f"Finalised evaluation for submission {job_id}")

    except Exception as e:
        print(f"Internal error evaluating {job_id}: {e}")
        _finalise(job_id, Verdict.IE, 0, 0, "", "Internal error")

    finally:
        # --- 8. Cleanup ---
        # Container is already removed by execute_driver_code
        if job_dir:
            cleanup_sandbox(job_dir)


# ---------------------------------------------------------------------------
# Periodic tasks (Celery Beat)
# ---------------------------------------------------------------------------

@_typed_task(name="worker.tasks.sweep_zombies")
def sweep_zombies() -> None:
    """Mark 'running' submissions stuck for > 2 minutes as IE (zombie sweep)."""
    with get_sync_db() as db:
        result = db.execute(
            text("""
                UPDATE submissions
                SET verdict = 'IE', status = 'completed'
                WHERE status = 'running'
                  AND updated_at < NOW() - INTERVAL '2 minutes'
                RETURNING id
            """)
        )
        zombie_ids = [str(r.id) for r in result.fetchall()]

    for job_id in zombie_ids:
        payload = json.dumps({"job_id": job_id, "status": "completed", "verdict": "IE"})
        _redis.publish(f"job_updates:{job_id}", payload)


@_typed_task(name="worker.tasks.sweep_sandbox_dirs")
def sweep_sandbox_dirs() -> None:
    """Remove sandbox job directories older than 15 minutes."""
    base = Path(settings.SANDBOX_BASE_DIR)
    if not base.exists():
        return

    cutoff = time.time() - 900  # 15 minutes
    for job_dir in base.iterdir():
        if job_dir.is_dir() and job_dir.stat().st_mtime < cutoff:
            shutil.rmtree(job_dir, ignore_errors=True)